services:
  rag-app:
    build: .
    ports:
      - "8501:8501"  # Streamlit
      - "8000:8000"  # FastAPI
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "python", "-c", "import socket; s=socket.socket(); s.connect(('127.0.0.1',8000))"]
      interval: 15s
      timeout: 3s
      retries: 5
